-- Reviewed Target Audience Fit changes only. Apply to the eight previously imported records.
-- No database connection/execution occurs during generation. Review this complete transaction before running.
-- Attendance, geography, planning, lifecycle, source identity and whole-conference verification timestamps are preserved.
begin;
set local standard_conforming_strings = on;
-- Money20/20 USA 2026
do $review$
declare c public.conferences%rowtype;
begin
  select * into c from public.conferences where id = '20000001-0000-4000-8000-000000000001' for update;
  if not found then raise exception 'Reviewed conference missing; transaction aborted'; end if;
  if c.id is distinct from '20000001-0000-4000-8000-000000000001'
    or c.edition_key is distinct from 'money2020:usa:2026'
    or c.is_demo is distinct from false
    or c.name is distinct from 'Money20/20 USA 2026'
    or c.start_date is distinct from '2026-10-18'
    or c.end_date is distinct from '2026-10-21'
    or c.city is distinct from 'Las Vegas'
    or c.country is distinct from 'United States'
    or c.region is distinct from NULL
    or c.vertical is distinct from 'fintech'
    or c.estimated_audience_size is distinct from NULL
    or c.lifecycle_status is distinct from 'scheduled'
    or c.needs_review is distinct from false
    or c.review_reason is distinct from NULL
    or c.source_url is distinct from 'https://us.money2020.com/'
    or c.source_name is distinct from 'Money20/20'
    or not (c.accepted_evidence @> '{"name":{"sourceUrl":"https://us.money2020.com/","sourceName":"Money20/20","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Money20/20 USA 2026 is an advertised upcoming edition."},"startDate":{"sourceUrl":"https://us.money2020.com/","sourceName":"Money20/20","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Upcoming edition starts 2026-10-18."},"endDate":{"sourceUrl":"https://us.money2020.com/","sourceName":"Money20/20","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Upcoming edition ends 2026-10-21."},"city":{"sourceUrl":"https://us.money2020.com/","sourceName":"Money20/20","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Las Vegas is the announced host city."},"country":{"sourceUrl":"https://us.money2020.com/","sourceName":"Money20/20","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Geographic normalization by researcher: Las Vegas is in United States; the source identifies the event city/venue."},"vertical":{"sourceUrl":"https://us.money2020.com/","sourceName":"Money20/20","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Editorial mapping to the existing fintech vertical, supported by: Banks, payments businesses, retailers, fintechs and senior executives are the described audience."},"lifecycleStatus":{"sourceUrl":"https://us.money2020.com/","sourceName":"Money20/20","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Organizer advertises this future edition; no cancellation notice was found in the checked edition information."},"targetAudience":{"sourceUrl":"https://us.money2020.com/","sourceName":"Money20/20","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Banks, payments businesses, retailers, fintechs and senior executives are the described audience."}}'::jsonb)
  then raise exception 'Conference facts/evidence changed; review before applying'; end if;
  if exists (select 1 from jsonb_each('{"audienceRelevance2026":{"sourceUrl":"https://us.money2020.com/agenda/content-pillars","sourceName":"Money20/20 USA","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official 2026 Borderless Financial Architecture pillar explicitly covers cross-border payments and settlements, modernization and interoperability for global commerce."}}'::jsonb) e
    where c.accepted_evidence ? e.key and c.accepted_evidence->e.key is distinct from e.value)
  then raise exception 'New evidence key conflicts; review before applying'; end if;
  if c.target_audience_fit is not distinct from 100
    and c.target_audience_assessment is not distinct from '{"input":{"rubricVersion":"grain-target-audience-v1","reviewState":"reviewed","reviewedAt":"2026-10-01T20:18:14Z","reviewedBy":"Developer-approved official-source assessment review","factors":{"audience":{"tags":[{"tag":"payment_companies","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"banks","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"fintech_businesses","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"relevance":{"tags":[{"tag":"payments","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"cross_border_payments","evidenceRefs":["audienceRelevance2026"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"leadership":{"tags":[{"tag":"relevant_senior_leaders","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null}}},"result":{"rubricVersion":"grain-target-audience-v1","supportedScoreFloor":100,"complete":true,"acceptedScore":100,"unresolvedFactors":[],"pendingReview":false,"components":[{"factor":"audience","maximum":60,"points":60,"resolved":true,"awardedTags":[{"tag":"payment_companies","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"relevance","maximum":25,"points":25,"resolved":true,"awardedTags":[{"tag":"cross_border_payments","evidenceRefs":["audienceRelevance2026"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"leadership","maximum":15,"points":15,"resolved":true,"awardedTags":[{"tag":"relevant_senior_leaders","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null}]}}'::jsonb
    and c.accepted_evidence @> '{"audienceRelevance2026":{"sourceUrl":"https://us.money2020.com/agenda/content-pillars","sourceName":"Money20/20 USA","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official 2026 Borderless Financial Architecture pillar explicitly covers cross-border payments and settlements, modernization and interoperability for global commerce."}}'::jsonb then
    null; -- Identical reviewed state: retry does not increment revision.
  elsif c.target_audience_fit is not distinct from NULL
    and c.target_audience_assessment is not distinct from '{"input":{"rubricVersion":"grain-target-audience-v1","reviewState":"reviewed","reviewedAt":"2026-10-01T19:07:08Z","reviewedBy":"Lead integration review of collected evidence","factors":{"audience":{"tags":[{"tag":"payment_companies","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"banks","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"fintech_businesses","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"relevance":{"tags":[{"tag":"payments","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":false,"resolutionEvidenceRefs":[],"unresolvedReason":"Explicit cross-border, FX or multi-currency relevance is not verified."},"leadership":{"tags":[{"tag":"relevant_senior_leaders","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null}}},"result":{"rubricVersion":"grain-target-audience-v1","supportedScoreFloor":90,"complete":false,"acceptedScore":null,"unresolvedFactors":[{"factor":"relevance","reason":"Explicit cross-border, FX or multi-currency relevance is not verified."}],"pendingReview":false,"components":[{"factor":"audience","maximum":60,"points":60,"resolved":true,"awardedTags":[{"tag":"payment_companies","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"relevance","maximum":25,"points":15,"resolved":false,"awardedTags":[{"tag":"payments","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":"Explicit cross-border, FX or multi-currency relevance is not verified."},{"factor":"leadership","maximum":15,"points":15,"resolved":true,"awardedTags":[{"tag":"relevant_senior_leaders","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null}]}}'::jsonb then
    update public.conferences
    set target_audience_fit = 100,
        target_audience_assessment = '{"input":{"rubricVersion":"grain-target-audience-v1","reviewState":"reviewed","reviewedAt":"2026-10-01T20:18:14Z","reviewedBy":"Developer-approved official-source assessment review","factors":{"audience":{"tags":[{"tag":"payment_companies","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"banks","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"fintech_businesses","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"relevance":{"tags":[{"tag":"payments","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"cross_border_payments","evidenceRefs":["audienceRelevance2026"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"leadership":{"tags":[{"tag":"relevant_senior_leaders","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null}}},"result":{"rubricVersion":"grain-target-audience-v1","supportedScoreFloor":100,"complete":true,"acceptedScore":100,"unresolvedFactors":[],"pendingReview":false,"components":[{"factor":"audience","maximum":60,"points":60,"resolved":true,"awardedTags":[{"tag":"payment_companies","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"relevance","maximum":25,"points":25,"resolved":true,"awardedTags":[{"tag":"cross_border_payments","evidenceRefs":["audienceRelevance2026"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"leadership","maximum":15,"points":15,"resolved":true,"awardedTags":[{"tag":"relevant_senior_leaders","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null}]}}'::jsonb,
        accepted_evidence = accepted_evidence || '{"audienceRelevance2026":{"sourceUrl":"https://us.money2020.com/agenda/content-pillars","sourceName":"Money20/20 USA","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official 2026 Borderless Financial Architecture pillar explicitly covers cross-border payments and settlements, modernization and interoperability for global commerce."}}'::jsonb,
        updated_at = now(), revision = revision + 1
    where id = '20000001-0000-4000-8000-000000000001';
  else raise exception 'Audience assessment changed; review before applying'; end if;
  insert into public.conference_observations (id, conference_id, edition_key, source_url, source_name, checked_at, verified_at, fetch_status, content_hash, evidence, extracted_facts, proposed_changes, issues, review_state, reviewed_at)
  values ('30000002-0000-4000-8000-000000000001', '20000001-0000-4000-8000-000000000001', 'money2020:usa:2026', 'https://us.money2020.com/agenda/content-pillars', 'Money20/20 USA', '2026-10-01T20:18:14Z', '2026-10-01T20:18:14Z', 'success', NULL, '[{"sourceUrl":"https://us.money2020.com/agenda/content-pillars","sourceName":"Money20/20 USA","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official 2026 Borderless Financial Architecture pillar explicitly covers cross-border payments and settlements, modernization and interoperability for global commerce."}]', '{"targetAudienceFit":100}', '{}', '["Overall ICP remains incomplete: estimatedAudienceSize, region. Attendance and geography were not changed."]', 'accepted', '2026-10-01T20:18:14Z') on conflict (id) do nothing;
  if exists (select 1 from public.conference_observations o where o.id = '30000002-0000-4000-8000-000000000001' and (
      o.id is distinct from '30000002-0000-4000-8000-000000000001'
      or o.conference_id is distinct from '20000001-0000-4000-8000-000000000001'
      or o.edition_key is distinct from 'money2020:usa:2026'
      or o.source_url is distinct from 'https://us.money2020.com/agenda/content-pillars'
      or o.source_name is distinct from 'Money20/20 USA'
      or o.checked_at is distinct from '2026-10-01T20:18:14Z'
      or o.verified_at is distinct from '2026-10-01T20:18:14Z'
      or o.fetch_status is distinct from 'success'
      or o.content_hash is distinct from NULL
      or o.evidence is distinct from '[{"sourceUrl":"https://us.money2020.com/agenda/content-pillars","sourceName":"Money20/20 USA","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official 2026 Borderless Financial Architecture pillar explicitly covers cross-border payments and settlements, modernization and interoperability for global commerce."}]'::jsonb
      or o.extracted_facts is distinct from '{"targetAudienceFit":100}'::jsonb
      or o.proposed_changes is distinct from '{}'::jsonb
      or o.issues is distinct from '["Overall ICP remains incomplete: estimatedAudienceSize, region. Attendance and geography were not changed."]'::jsonb
      or o.review_state is distinct from 'accepted'
      or o.reviewed_at is distinct from '2026-10-01T20:18:14Z'))
  then raise exception 'Review observation ID conflicts; transaction aborted'; end if;
end $review$;
-- AFP 2026 Finance & Treasury Conference
do $review$
declare c public.conferences%rowtype;
begin
  select * into c from public.conferences where id = '20000001-0000-4000-8000-000000000002' for update;
  if not found then raise exception 'Reviewed conference missing; transaction aborted'; end if;
  if c.id is distinct from '20000001-0000-4000-8000-000000000002'
    or c.edition_key is distinct from 'afp:annual:2026'
    or c.is_demo is distinct from false
    or c.name is distinct from 'AFP 2026 Finance & Treasury Conference'
    or c.start_date is distinct from '2026-11-08'
    or c.end_date is distinct from '2026-11-11'
    or c.city is distinct from 'Las Vegas'
    or c.country is distinct from 'United States'
    or c.region is distinct from NULL
    or c.vertical is distinct from 'fintech'
    or c.estimated_audience_size is distinct from NULL
    or c.lifecycle_status is distinct from 'scheduled'
    or c.needs_review is distinct from false
    or c.review_reason is distinct from NULL
    or c.source_url is distinct from 'https://conference.financialprofessionals.org/'
    or c.source_name is distinct from 'Association for Financial Professionals'
    or not (c.accepted_evidence @> '{"name":{"sourceUrl":"https://conference.financialprofessionals.org/","sourceName":"Association for Financial Professionals","checkedAt":"2026-10-01T18:53:01Z","excerpt":"AFP 2026 Finance & Treasury Conference is an advertised upcoming edition."},"startDate":{"sourceUrl":"https://conference.financialprofessionals.org/","sourceName":"Association for Financial Professionals","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Upcoming edition starts 2026-11-08."},"endDate":{"sourceUrl":"https://conference.financialprofessionals.org/","sourceName":"Association for Financial Professionals","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Upcoming edition ends 2026-11-11."},"city":{"sourceUrl":"https://conference.financialprofessionals.org/","sourceName":"Association for Financial Professionals","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Las Vegas is the announced host city."},"country":{"sourceUrl":"https://conference.financialprofessionals.org/","sourceName":"Association for Financial Professionals","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Geographic normalization by researcher: Las Vegas is in United States; the source identifies the event city/venue."},"vertical":{"sourceUrl":"https://conference.financialprofessionals.org/","sourceName":"Association for Financial Professionals","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Editorial mapping to the existing fintech vertical, supported by: Corporate treasury, finance, payments and FP&A practitioners, including CFO-office leaders, are the stated audience."},"lifecycleStatus":{"sourceUrl":"https://conference.financialprofessionals.org/","sourceName":"Association for Financial Professionals","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Organizer advertises this future edition; no cancellation notice was found in the checked edition information."},"targetAudience":{"sourceUrl":"https://conference.financialprofessionals.org/","sourceName":"Association for Financial Professionals","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Corporate treasury, finance, payments and FP&A practitioners, including CFO-office leaders, are the stated audience."}}'::jsonb)
  then raise exception 'Conference facts/evidence changed; review before applying'; end if;
  if exists (select 1 from jsonb_each('{"audienceRelevance2026":{"sourceUrl":"https://conference.financialprofessionals.org/program/sessions/sessions","sourceName":"Association for Financial Professionals","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official AFP 2026 sessions address cross-currency payments, cross-border settlement and liquidity, FX balance-sheet hedging and treasury FX workflows."}}'::jsonb) e
    where c.accepted_evidence ? e.key and c.accepted_evidence->e.key is distinct from e.value)
  then raise exception 'New evidence key conflicts; review before applying'; end if;
  if c.target_audience_fit is not distinct from 100
    and c.target_audience_assessment is not distinct from '{"input":{"rubricVersion":"grain-target-audience-v1","reviewState":"reviewed","reviewedAt":"2026-10-01T20:18:14Z","reviewedBy":"Developer-approved official-source assessment review","factors":{"audience":{"tags":[{"tag":"corporate_treasury","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"corporate_finance","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"relevance":{"tags":[{"tag":"payments","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"cross_border_payments","evidenceRefs":["audienceRelevance2026"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"leadership":{"tags":[{"tag":"senior_finance_payment_executives","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null}}},"result":{"rubricVersion":"grain-target-audience-v1","supportedScoreFloor":100,"complete":true,"acceptedScore":100,"unresolvedFactors":[],"pendingReview":false,"components":[{"factor":"audience","maximum":60,"points":60,"resolved":true,"awardedTags":[{"tag":"corporate_treasury","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"relevance","maximum":25,"points":25,"resolved":true,"awardedTags":[{"tag":"cross_border_payments","evidenceRefs":["audienceRelevance2026"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"leadership","maximum":15,"points":15,"resolved":true,"awardedTags":[{"tag":"senior_finance_payment_executives","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null}]}}'::jsonb
    and c.accepted_evidence @> '{"audienceRelevance2026":{"sourceUrl":"https://conference.financialprofessionals.org/program/sessions/sessions","sourceName":"Association for Financial Professionals","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official AFP 2026 sessions address cross-currency payments, cross-border settlement and liquidity, FX balance-sheet hedging and treasury FX workflows."}}'::jsonb then
    null; -- Identical reviewed state: retry does not increment revision.
  elsif c.target_audience_fit is not distinct from NULL
    and c.target_audience_assessment is not distinct from '{"input":{"rubricVersion":"grain-target-audience-v1","reviewState":"reviewed","reviewedAt":"2026-10-01T19:07:08Z","reviewedBy":"Lead integration review of collected evidence","factors":{"audience":{"tags":[{"tag":"corporate_treasury","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"corporate_finance","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"relevance":{"tags":[{"tag":"payments","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":false,"resolutionEvidenceRefs":[],"unresolvedReason":"Explicit cross-border, FX or multi-currency relevance is not verified."},"leadership":{"tags":[{"tag":"senior_finance_payment_executives","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null}}},"result":{"rubricVersion":"grain-target-audience-v1","supportedScoreFloor":90,"complete":false,"acceptedScore":null,"unresolvedFactors":[{"factor":"relevance","reason":"Explicit cross-border, FX or multi-currency relevance is not verified."}],"pendingReview":false,"components":[{"factor":"audience","maximum":60,"points":60,"resolved":true,"awardedTags":[{"tag":"corporate_treasury","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"relevance","maximum":25,"points":15,"resolved":false,"awardedTags":[{"tag":"payments","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":"Explicit cross-border, FX or multi-currency relevance is not verified."},{"factor":"leadership","maximum":15,"points":15,"resolved":true,"awardedTags":[{"tag":"senior_finance_payment_executives","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null}]}}'::jsonb then
    update public.conferences
    set target_audience_fit = 100,
        target_audience_assessment = '{"input":{"rubricVersion":"grain-target-audience-v1","reviewState":"reviewed","reviewedAt":"2026-10-01T20:18:14Z","reviewedBy":"Developer-approved official-source assessment review","factors":{"audience":{"tags":[{"tag":"corporate_treasury","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"corporate_finance","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"relevance":{"tags":[{"tag":"payments","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"cross_border_payments","evidenceRefs":["audienceRelevance2026"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"leadership":{"tags":[{"tag":"senior_finance_payment_executives","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null}}},"result":{"rubricVersion":"grain-target-audience-v1","supportedScoreFloor":100,"complete":true,"acceptedScore":100,"unresolvedFactors":[],"pendingReview":false,"components":[{"factor":"audience","maximum":60,"points":60,"resolved":true,"awardedTags":[{"tag":"corporate_treasury","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"relevance","maximum":25,"points":25,"resolved":true,"awardedTags":[{"tag":"cross_border_payments","evidenceRefs":["audienceRelevance2026"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"leadership","maximum":15,"points":15,"resolved":true,"awardedTags":[{"tag":"senior_finance_payment_executives","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null}]}}'::jsonb,
        accepted_evidence = accepted_evidence || '{"audienceRelevance2026":{"sourceUrl":"https://conference.financialprofessionals.org/program/sessions/sessions","sourceName":"Association for Financial Professionals","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official AFP 2026 sessions address cross-currency payments, cross-border settlement and liquidity, FX balance-sheet hedging and treasury FX workflows."}}'::jsonb,
        updated_at = now(), revision = revision + 1
    where id = '20000001-0000-4000-8000-000000000002';
  else raise exception 'Audience assessment changed; review before applying'; end if;
  insert into public.conference_observations (id, conference_id, edition_key, source_url, source_name, checked_at, verified_at, fetch_status, content_hash, evidence, extracted_facts, proposed_changes, issues, review_state, reviewed_at)
  values ('30000002-0000-4000-8000-000000000002', '20000001-0000-4000-8000-000000000002', 'afp:annual:2026', 'https://conference.financialprofessionals.org/program/sessions/sessions', 'Association for Financial Professionals', '2026-10-01T20:18:14Z', '2026-10-01T20:18:14Z', 'success', NULL, '[{"sourceUrl":"https://conference.financialprofessionals.org/program/sessions/sessions","sourceName":"Association for Financial Professionals","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official AFP 2026 sessions address cross-currency payments, cross-border settlement and liquidity, FX balance-sheet hedging and treasury FX workflows."}]', '{"targetAudienceFit":100}', '{}', '["Overall ICP remains incomplete: estimatedAudienceSize, region. Attendance and geography were not changed."]', 'accepted', '2026-10-01T20:18:14Z') on conflict (id) do nothing;
  if exists (select 1 from public.conference_observations o where o.id = '30000002-0000-4000-8000-000000000002' and (
      o.id is distinct from '30000002-0000-4000-8000-000000000002'
      or o.conference_id is distinct from '20000001-0000-4000-8000-000000000002'
      or o.edition_key is distinct from 'afp:annual:2026'
      or o.source_url is distinct from 'https://conference.financialprofessionals.org/program/sessions/sessions'
      or o.source_name is distinct from 'Association for Financial Professionals'
      or o.checked_at is distinct from '2026-10-01T20:18:14Z'
      or o.verified_at is distinct from '2026-10-01T20:18:14Z'
      or o.fetch_status is distinct from 'success'
      or o.content_hash is distinct from NULL
      or o.evidence is distinct from '[{"sourceUrl":"https://conference.financialprofessionals.org/program/sessions/sessions","sourceName":"Association for Financial Professionals","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official AFP 2026 sessions address cross-currency payments, cross-border settlement and liquidity, FX balance-sheet hedging and treasury FX workflows."}]'::jsonb
      or o.extracted_facts is distinct from '{"targetAudienceFit":100}'::jsonb
      or o.proposed_changes is distinct from '{}'::jsonb
      or o.issues is distinct from '["Overall ICP remains incomplete: estimatedAudienceSize, region. Attendance and geography were not changed."]'::jsonb
      or o.review_state is distinct from 'accepted'
      or o.reviewed_at is distinct from '2026-10-01T20:18:14Z'))
  then raise exception 'Review observation ID conflicts; transaction aborted'; end if;
end $review$;
-- FinTech Connect 2026
do $review$
declare c public.conferences%rowtype;
begin
  select * into c from public.conferences where id = '20000001-0000-4000-8000-000000000003' for update;
  if not found then raise exception 'Reviewed conference missing; transaction aborted'; end if;
  if c.id is distinct from '20000001-0000-4000-8000-000000000003'
    or c.edition_key is distinct from 'fintechconnect:london:2026'
    or c.is_demo is distinct from false
    or c.name is distinct from 'FinTech Connect 2026'
    or c.start_date is distinct from '2026-12-01'
    or c.end_date is distinct from '2026-12-02'
    or c.city is distinct from 'London'
    or c.country is distinct from 'United Kingdom'
    or c.region is distinct from 'uk-southeast'
    or c.vertical is distinct from 'fintech'
    or c.estimated_audience_size is distinct from 6000
    or c.lifecycle_status is distinct from 'scheduled'
    or c.needs_review is distinct from false
    or c.review_reason is distinct from NULL
    or c.source_url is distinct from 'https://www.fintechconnect.com/'
    or c.source_name is distinct from 'FinTech Connect'
    or not (c.accepted_evidence @> '{"name":{"sourceUrl":"https://www.fintechconnect.com/","sourceName":"FinTech Connect","checkedAt":"2026-10-01T18:53:01Z","excerpt":"FinTech Connect 2026 is an advertised upcoming edition."},"startDate":{"sourceUrl":"https://www.fintechconnect.com/","sourceName":"FinTech Connect","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Upcoming edition starts 2026-12-01."},"endDate":{"sourceUrl":"https://www.fintechconnect.com/","sourceName":"FinTech Connect","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Upcoming edition ends 2026-12-02."},"city":{"sourceUrl":"https://www.fintechconnect.com/","sourceName":"FinTech Connect","checkedAt":"2026-10-01T18:53:01Z","excerpt":"London is the announced host city."},"country":{"sourceUrl":"https://www.fintechconnect.com/","sourceName":"FinTech Connect","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Geographic normalization by researcher: London is in United Kingdom; the source identifies the event city/venue."},"vertical":{"sourceUrl":"https://www.fintechconnect.com/","sourceName":"FinTech Connect","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Editorial mapping to the existing fintech vertical, supported by: Financial institutions and fintech firms are addressed; payments and business banking are listed tracks."},"lifecycleStatus":{"sourceUrl":"https://www.fintechconnect.com/","sourceName":"FinTech Connect","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Organizer advertises this future edition; no cancellation notice was found in the checked edition information."},"targetAudience":{"sourceUrl":"https://www.fintechconnect.com/","sourceName":"FinTech Connect","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Financial institutions and fintech firms are addressed; payments and business banking are listed tracks."},"region":{"sourceUrl":"https://www.fintechconnect.com/","sourceName":"FinTech Connect","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Editorial application of the existing predefined region uk-southeast to London; not a maps/distance calculation."},"estimatedAudienceSize":{"sourceUrl":"https://www.fintechconnect.com/","sourceName":"FinTech Connect","checkedAt":"2026-10-01T18:53:01Z","excerpt":"The 2026 registration-progress section explicitly names a 6,000 visitor target; this is expected attendance, not actual attendance."}}'::jsonb)
  then raise exception 'Conference facts/evidence changed; review before applying'; end if;
  if exists (select 1 from jsonb_each('{"audienceTreasury2026":{"sourceUrl":"https://www.fintechconnect.com/sponsor-exhibit","sourceName":"FinTech Connect","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official 2026 audience section identifies corporate CFOs, Group Treasurers and Heads of Cash and Liquidity from FTSE 100/250 finance functions; their stated focus includes cross-border payments and cross-border treasury operations."},"audiencePayments2026":{"sourceUrl":"https://www.fintechconnect.com/payment-innovation","sourceName":"FinTech Connect","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official 2026 Payments Innovation track lists Heads of Cross-Border Payments, VP/Director Global Payments and Chief Payments Officers as attendees, and explicitly includes cross-border payment reform among attendee benefits."}}'::jsonb) e
    where c.accepted_evidence ? e.key and c.accepted_evidence->e.key is distinct from e.value)
  then raise exception 'New evidence key conflicts; review before applying'; end if;
  if c.target_audience_fit is not distinct from 100
    and c.target_audience_assessment is not distinct from '{"input":{"rubricVersion":"grain-target-audience-v1","reviewState":"reviewed","reviewedAt":"2026-10-01T20:18:14Z","reviewedBy":"Developer-approved official-source assessment review","factors":{"audience":{"tags":[{"tag":"financial_institutions","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"fintech_businesses","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"corporate_treasury","evidenceRefs":["audienceTreasury2026"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"relevance":{"tags":[{"tag":"payments","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"cross_border_payments","evidenceRefs":["audiencePayments2026"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"leadership":{"tags":[{"tag":"corporate_treasurers","evidenceRefs":["audienceTreasury2026"],"reviewed":true},{"tag":"senior_finance_payment_executives","evidenceRefs":["audiencePayments2026"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null}}},"result":{"rubricVersion":"grain-target-audience-v1","supportedScoreFloor":100,"complete":true,"acceptedScore":100,"unresolvedFactors":[],"pendingReview":false,"components":[{"factor":"audience","maximum":60,"points":60,"resolved":true,"awardedTags":[{"tag":"corporate_treasury","evidenceRefs":["audienceTreasury2026"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"relevance","maximum":25,"points":25,"resolved":true,"awardedTags":[{"tag":"cross_border_payments","evidenceRefs":["audiencePayments2026"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"leadership","maximum":15,"points":15,"resolved":true,"awardedTags":[{"tag":"corporate_treasurers","evidenceRefs":["audienceTreasury2026"]},{"tag":"senior_finance_payment_executives","evidenceRefs":["audiencePayments2026"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null}]}}'::jsonb
    and c.accepted_evidence @> '{"audienceTreasury2026":{"sourceUrl":"https://www.fintechconnect.com/sponsor-exhibit","sourceName":"FinTech Connect","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official 2026 audience section identifies corporate CFOs, Group Treasurers and Heads of Cash and Liquidity from FTSE 100/250 finance functions; their stated focus includes cross-border payments and cross-border treasury operations."},"audiencePayments2026":{"sourceUrl":"https://www.fintechconnect.com/payment-innovation","sourceName":"FinTech Connect","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official 2026 Payments Innovation track lists Heads of Cross-Border Payments, VP/Director Global Payments and Chief Payments Officers as attendees, and explicitly includes cross-border payment reform among attendee benefits."}}'::jsonb then
    null; -- Identical reviewed state: retry does not increment revision.
  elsif c.target_audience_fit is not distinct from NULL
    and c.target_audience_assessment is not distinct from '{"input":{"rubricVersion":"grain-target-audience-v1","reviewState":"reviewed","reviewedAt":"2026-10-01T19:07:08Z","reviewedBy":"Lead integration review of collected evidence","factors":{"audience":{"tags":[{"tag":"financial_institutions","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"fintech_businesses","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":false,"resolutionEvidenceRefs":[],"unresolvedReason":"Direct payment-company, corporate-treasury or merchant-FX audience is not verified."},"relevance":{"tags":[{"tag":"payments","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":false,"resolutionEvidenceRefs":[],"unresolvedReason":"Explicit cross-border, FX or multi-currency relevance is not verified."},"leadership":{"tags":[],"resolved":false,"resolutionEvidenceRefs":[],"unresolvedReason":"Relevant leadership seniority is not verified in the collected audience evidence."}}},"result":{"rubricVersion":"grain-target-audience-v1","supportedScoreFloor":60,"complete":false,"acceptedScore":null,"unresolvedFactors":[{"factor":"audience","reason":"Direct payment-company, corporate-treasury or merchant-FX audience is not verified."},{"factor":"relevance","reason":"Explicit cross-border, FX or multi-currency relevance is not verified."},{"factor":"leadership","reason":"Relevant leadership seniority is not verified in the collected audience evidence."}],"pendingReview":false,"components":[{"factor":"audience","maximum":60,"points":45,"resolved":false,"awardedTags":[{"tag":"financial_institutions","evidenceRefs":["targetAudience"]},{"tag":"fintech_businesses","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":"Direct payment-company, corporate-treasury or merchant-FX audience is not verified."},{"factor":"relevance","maximum":25,"points":15,"resolved":false,"awardedTags":[{"tag":"payments","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":"Explicit cross-border, FX or multi-currency relevance is not verified."},{"factor":"leadership","maximum":15,"points":null,"resolved":false,"awardedTags":[],"resolutionEvidenceRefs":[],"unresolvedReason":"Relevant leadership seniority is not verified in the collected audience evidence."}]}}'::jsonb then
    update public.conferences
    set target_audience_fit = 100,
        target_audience_assessment = '{"input":{"rubricVersion":"grain-target-audience-v1","reviewState":"reviewed","reviewedAt":"2026-10-01T20:18:14Z","reviewedBy":"Developer-approved official-source assessment review","factors":{"audience":{"tags":[{"tag":"financial_institutions","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"fintech_businesses","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"corporate_treasury","evidenceRefs":["audienceTreasury2026"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"relevance":{"tags":[{"tag":"payments","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"cross_border_payments","evidenceRefs":["audiencePayments2026"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"leadership":{"tags":[{"tag":"corporate_treasurers","evidenceRefs":["audienceTreasury2026"],"reviewed":true},{"tag":"senior_finance_payment_executives","evidenceRefs":["audiencePayments2026"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null}}},"result":{"rubricVersion":"grain-target-audience-v1","supportedScoreFloor":100,"complete":true,"acceptedScore":100,"unresolvedFactors":[],"pendingReview":false,"components":[{"factor":"audience","maximum":60,"points":60,"resolved":true,"awardedTags":[{"tag":"corporate_treasury","evidenceRefs":["audienceTreasury2026"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"relevance","maximum":25,"points":25,"resolved":true,"awardedTags":[{"tag":"cross_border_payments","evidenceRefs":["audiencePayments2026"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"leadership","maximum":15,"points":15,"resolved":true,"awardedTags":[{"tag":"corporate_treasurers","evidenceRefs":["audienceTreasury2026"]},{"tag":"senior_finance_payment_executives","evidenceRefs":["audiencePayments2026"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null}]}}'::jsonb,
        accepted_evidence = accepted_evidence || '{"audienceTreasury2026":{"sourceUrl":"https://www.fintechconnect.com/sponsor-exhibit","sourceName":"FinTech Connect","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official 2026 audience section identifies corporate CFOs, Group Treasurers and Heads of Cash and Liquidity from FTSE 100/250 finance functions; their stated focus includes cross-border payments and cross-border treasury operations."},"audiencePayments2026":{"sourceUrl":"https://www.fintechconnect.com/payment-innovation","sourceName":"FinTech Connect","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official 2026 Payments Innovation track lists Heads of Cross-Border Payments, VP/Director Global Payments and Chief Payments Officers as attendees, and explicitly includes cross-border payment reform among attendee benefits."}}'::jsonb,
        updated_at = now(), revision = revision + 1
    where id = '20000001-0000-4000-8000-000000000003';
  else raise exception 'Audience assessment changed; review before applying'; end if;
  insert into public.conference_observations (id, conference_id, edition_key, source_url, source_name, checked_at, verified_at, fetch_status, content_hash, evidence, extracted_facts, proposed_changes, issues, review_state, reviewed_at)
  values ('30000002-0000-4000-8000-000000000003', '20000001-0000-4000-8000-000000000003', 'fintechconnect:london:2026', 'https://www.fintechconnect.com/sponsor-exhibit', 'FinTech Connect', '2026-10-01T20:18:14Z', '2026-10-01T20:18:14Z', 'success', NULL, '[{"sourceUrl":"https://www.fintechconnect.com/sponsor-exhibit","sourceName":"FinTech Connect","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official 2026 audience section identifies corporate CFOs, Group Treasurers and Heads of Cash and Liquidity from FTSE 100/250 finance functions; their stated focus includes cross-border payments and cross-border treasury operations."},{"sourceUrl":"https://www.fintechconnect.com/payment-innovation","sourceName":"FinTech Connect","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official 2026 Payments Innovation track lists Heads of Cross-Border Payments, VP/Director Global Payments and Chief Payments Officers as attendees, and explicitly includes cross-border payment reform among attendee benefits."}]', '{"targetAudienceFit":100}', '{}', '[]', 'accepted', '2026-10-01T20:18:14Z') on conflict (id) do nothing;
  if exists (select 1 from public.conference_observations o where o.id = '30000002-0000-4000-8000-000000000003' and (
      o.id is distinct from '30000002-0000-4000-8000-000000000003'
      or o.conference_id is distinct from '20000001-0000-4000-8000-000000000003'
      or o.edition_key is distinct from 'fintechconnect:london:2026'
      or o.source_url is distinct from 'https://www.fintechconnect.com/sponsor-exhibit'
      or o.source_name is distinct from 'FinTech Connect'
      or o.checked_at is distinct from '2026-10-01T20:18:14Z'
      or o.verified_at is distinct from '2026-10-01T20:18:14Z'
      or o.fetch_status is distinct from 'success'
      or o.content_hash is distinct from NULL
      or o.evidence is distinct from '[{"sourceUrl":"https://www.fintechconnect.com/sponsor-exhibit","sourceName":"FinTech Connect","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official 2026 audience section identifies corporate CFOs, Group Treasurers and Heads of Cash and Liquidity from FTSE 100/250 finance functions; their stated focus includes cross-border payments and cross-border treasury operations."},{"sourceUrl":"https://www.fintechconnect.com/payment-innovation","sourceName":"FinTech Connect","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official 2026 Payments Innovation track lists Heads of Cross-Border Payments, VP/Director Global Payments and Chief Payments Officers as attendees, and explicitly includes cross-border payment reform among attendee benefits."}]'::jsonb
      or o.extracted_facts is distinct from '{"targetAudienceFit":100}'::jsonb
      or o.proposed_changes is distinct from '{}'::jsonb
      or o.issues is distinct from '[]'::jsonb
      or o.review_state is distinct from 'accepted'
      or o.reviewed_at is distinct from '2026-10-01T20:18:14Z'))
  then raise exception 'Review observation ID conflicts; transaction aborted'; end if;
end $review$;
-- PAY360 2027
do $review$
declare c public.conferences%rowtype;
begin
  select * into c from public.conferences where id = '20000001-0000-4000-8000-000000000004' for update;
  if not found then raise exception 'Reviewed conference missing; transaction aborted'; end if;
  if c.id is distinct from '20000001-0000-4000-8000-000000000004'
    or c.edition_key is distinct from 'pay360:london:2027'
    or c.is_demo is distinct from false
    or c.name is distinct from 'PAY360 2027'
    or c.start_date is distinct from '2027-04-21'
    or c.end_date is distinct from '2027-04-22'
    or c.city is distinct from 'London'
    or c.country is distinct from 'United Kingdom'
    or c.region is distinct from 'uk-southeast'
    or c.vertical is distinct from 'fintech'
    or c.estimated_audience_size is distinct from NULL
    or c.lifecycle_status is distinct from 'scheduled'
    or c.needs_review is distinct from false
    or c.review_reason is distinct from NULL
    or c.source_url is distinct from 'https://pay360event.com/'
    or c.source_name is distinct from 'The Payments Association / PAY360'
    or not (c.accepted_evidence @> '{"name":{"sourceUrl":"https://pay360event.com/","sourceName":"The Payments Association / PAY360","checkedAt":"2026-10-01T18:53:01Z","excerpt":"PAY360 2027 is an advertised upcoming edition."},"startDate":{"sourceUrl":"https://pay360event.com/","sourceName":"The Payments Association / PAY360","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Upcoming edition starts 2027-04-21."},"endDate":{"sourceUrl":"https://pay360event.com/","sourceName":"The Payments Association / PAY360","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Upcoming edition ends 2027-04-22."},"city":{"sourceUrl":"https://pay360event.com/","sourceName":"The Payments Association / PAY360","checkedAt":"2026-10-01T18:53:01Z","excerpt":"London is the announced host city."},"country":{"sourceUrl":"https://pay360event.com/","sourceName":"The Payments Association / PAY360","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Geographic normalization by researcher: London is in United Kingdom; the source identifies the event city/venue."},"vertical":{"sourceUrl":"https://pay360event.com/","sourceName":"The Payments Association / PAY360","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Editorial mapping to the existing fintech vertical, supported by: The 2027 audience description includes banks, merchants, payment infrastructure, card networks, acquirers and processors."},"lifecycleStatus":{"sourceUrl":"https://pay360event.com/","sourceName":"The Payments Association / PAY360","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Organizer advertises this future edition; no cancellation notice was found in the checked edition information."},"targetAudience":{"sourceUrl":"https://pay360event.com/","sourceName":"The Payments Association / PAY360","checkedAt":"2026-10-01T18:53:01Z","excerpt":"The 2027 audience description includes banks, merchants, payment infrastructure, card networks, acquirers and processors."},"region":{"sourceUrl":"https://pay360event.com/","sourceName":"The Payments Association / PAY360","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Editorial application of the existing predefined region uk-southeast to London; not a maps/distance calculation."}}'::jsonb)
  then raise exception 'Conference facts/evidence changed; review before applying'; end if;
  if exists (select 1 from jsonb_each('{"audienceRelevance2027":{"sourceUrl":"https://pay360event.com/","sourceName":"The Payments Association / PAY360","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official PAY360 2027 page explicitly lists cross-border payments among core 2027 themes and targets senior payments decision-makers; the 2027 lineup includes the Chief Payments Officer of HSBC."}}'::jsonb) e
    where c.accepted_evidence ? e.key and c.accepted_evidence->e.key is distinct from e.value)
  then raise exception 'New evidence key conflicts; review before applying'; end if;
  if c.target_audience_fit is not distinct from 100
    and c.target_audience_assessment is not distinct from '{"input":{"rubricVersion":"grain-target-audience-v1","reviewState":"reviewed","reviewedAt":"2026-10-01T20:18:14Z","reviewedBy":"Developer-approved official-source assessment review","factors":{"audience":{"tags":[{"tag":"acquirers","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"processors","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"banks","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"relevance":{"tags":[{"tag":"payments","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"cross_border_payments","evidenceRefs":["audienceRelevance2027"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"leadership":{"tags":[{"tag":"senior_finance_payment_executives","evidenceRefs":["audienceRelevance2027"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null}}},"result":{"rubricVersion":"grain-target-audience-v1","supportedScoreFloor":100,"complete":true,"acceptedScore":100,"unresolvedFactors":[],"pendingReview":false,"components":[{"factor":"audience","maximum":60,"points":60,"resolved":true,"awardedTags":[{"tag":"acquirers","evidenceRefs":["targetAudience"]},{"tag":"processors","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"relevance","maximum":25,"points":25,"resolved":true,"awardedTags":[{"tag":"cross_border_payments","evidenceRefs":["audienceRelevance2027"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"leadership","maximum":15,"points":15,"resolved":true,"awardedTags":[{"tag":"senior_finance_payment_executives","evidenceRefs":["audienceRelevance2027"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null}]}}'::jsonb
    and c.accepted_evidence @> '{"audienceRelevance2027":{"sourceUrl":"https://pay360event.com/","sourceName":"The Payments Association / PAY360","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official PAY360 2027 page explicitly lists cross-border payments among core 2027 themes and targets senior payments decision-makers; the 2027 lineup includes the Chief Payments Officer of HSBC."}}'::jsonb then
    null; -- Identical reviewed state: retry does not increment revision.
  elsif c.target_audience_fit is not distinct from NULL
    and c.target_audience_assessment is not distinct from '{"input":{"rubricVersion":"grain-target-audience-v1","reviewState":"reviewed","reviewedAt":"2026-10-01T19:07:08Z","reviewedBy":"Lead integration review of collected evidence","factors":{"audience":{"tags":[{"tag":"acquirers","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"processors","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"banks","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"relevance":{"tags":[{"tag":"payments","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":false,"resolutionEvidenceRefs":[],"unresolvedReason":"Explicit cross-border, FX or multi-currency relevance is not verified."},"leadership":{"tags":[],"resolved":false,"resolutionEvidenceRefs":[],"unresolvedReason":"Relevant leadership seniority is not verified in the collected audience evidence."}}},"result":{"rubricVersion":"grain-target-audience-v1","supportedScoreFloor":75,"complete":false,"acceptedScore":null,"unresolvedFactors":[{"factor":"relevance","reason":"Explicit cross-border, FX or multi-currency relevance is not verified."},{"factor":"leadership","reason":"Relevant leadership seniority is not verified in the collected audience evidence."}],"pendingReview":false,"components":[{"factor":"audience","maximum":60,"points":60,"resolved":true,"awardedTags":[{"tag":"acquirers","evidenceRefs":["targetAudience"]},{"tag":"processors","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"relevance","maximum":25,"points":15,"resolved":false,"awardedTags":[{"tag":"payments","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":"Explicit cross-border, FX or multi-currency relevance is not verified."},{"factor":"leadership","maximum":15,"points":null,"resolved":false,"awardedTags":[],"resolutionEvidenceRefs":[],"unresolvedReason":"Relevant leadership seniority is not verified in the collected audience evidence."}]}}'::jsonb then
    update public.conferences
    set target_audience_fit = 100,
        target_audience_assessment = '{"input":{"rubricVersion":"grain-target-audience-v1","reviewState":"reviewed","reviewedAt":"2026-10-01T20:18:14Z","reviewedBy":"Developer-approved official-source assessment review","factors":{"audience":{"tags":[{"tag":"acquirers","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"processors","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"banks","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"relevance":{"tags":[{"tag":"payments","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"cross_border_payments","evidenceRefs":["audienceRelevance2027"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"leadership":{"tags":[{"tag":"senior_finance_payment_executives","evidenceRefs":["audienceRelevance2027"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null}}},"result":{"rubricVersion":"grain-target-audience-v1","supportedScoreFloor":100,"complete":true,"acceptedScore":100,"unresolvedFactors":[],"pendingReview":false,"components":[{"factor":"audience","maximum":60,"points":60,"resolved":true,"awardedTags":[{"tag":"acquirers","evidenceRefs":["targetAudience"]},{"tag":"processors","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"relevance","maximum":25,"points":25,"resolved":true,"awardedTags":[{"tag":"cross_border_payments","evidenceRefs":["audienceRelevance2027"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"leadership","maximum":15,"points":15,"resolved":true,"awardedTags":[{"tag":"senior_finance_payment_executives","evidenceRefs":["audienceRelevance2027"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null}]}}'::jsonb,
        accepted_evidence = accepted_evidence || '{"audienceRelevance2027":{"sourceUrl":"https://pay360event.com/","sourceName":"The Payments Association / PAY360","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official PAY360 2027 page explicitly lists cross-border payments among core 2027 themes and targets senior payments decision-makers; the 2027 lineup includes the Chief Payments Officer of HSBC."}}'::jsonb,
        updated_at = now(), revision = revision + 1
    where id = '20000001-0000-4000-8000-000000000004';
  else raise exception 'Audience assessment changed; review before applying'; end if;
  insert into public.conference_observations (id, conference_id, edition_key, source_url, source_name, checked_at, verified_at, fetch_status, content_hash, evidence, extracted_facts, proposed_changes, issues, review_state, reviewed_at)
  values ('30000002-0000-4000-8000-000000000004', '20000001-0000-4000-8000-000000000004', 'pay360:london:2027', 'https://pay360event.com/', 'The Payments Association / PAY360', '2026-10-01T20:18:14Z', '2026-10-01T20:18:14Z', 'success', NULL, '[{"sourceUrl":"https://pay360event.com/","sourceName":"The Payments Association / PAY360","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official PAY360 2027 page explicitly lists cross-border payments among core 2027 themes and targets senior payments decision-makers; the 2027 lineup includes the Chief Payments Officer of HSBC."}]', '{"targetAudienceFit":100}', '{}', '["Overall ICP remains incomplete: estimatedAudienceSize. Attendance and geography were not changed."]', 'accepted', '2026-10-01T20:18:14Z') on conflict (id) do nothing;
  if exists (select 1 from public.conference_observations o where o.id = '30000002-0000-4000-8000-000000000004' and (
      o.id is distinct from '30000002-0000-4000-8000-000000000004'
      or o.conference_id is distinct from '20000001-0000-4000-8000-000000000004'
      or o.edition_key is distinct from 'pay360:london:2027'
      or o.source_url is distinct from 'https://pay360event.com/'
      or o.source_name is distinct from 'The Payments Association / PAY360'
      or o.checked_at is distinct from '2026-10-01T20:18:14Z'
      or o.verified_at is distinct from '2026-10-01T20:18:14Z'
      or o.fetch_status is distinct from 'success'
      or o.content_hash is distinct from NULL
      or o.evidence is distinct from '[{"sourceUrl":"https://pay360event.com/","sourceName":"The Payments Association / PAY360","checkedAt":"2026-10-01T20:18:14Z","excerpt":"Official PAY360 2027 page explicitly lists cross-border payments among core 2027 themes and targets senior payments decision-makers; the 2027 lineup includes the Chief Payments Officer of HSBC."}]'::jsonb
      or o.extracted_facts is distinct from '{"targetAudienceFit":100}'::jsonb
      or o.proposed_changes is distinct from '{}'::jsonb
      or o.issues is distinct from '["Overall ICP remains incomplete: estimatedAudienceSize. Attendance and geography were not changed."]'::jsonb
      or o.review_state is distinct from 'accepted'
      or o.reviewed_at is distinct from '2026-10-01T20:18:14Z'))
  then raise exception 'Review observation ID conflicts; transaction aborted'; end if;
end $review$;
-- Money20/20 Asia 2027
do $review$
declare c public.conferences%rowtype;
begin
  select * into c from public.conferences where id = '20000001-0000-4000-8000-000000000005' for update;
  if not found then raise exception 'Reviewed conference missing; transaction aborted'; end if;
  if c.id is distinct from '20000001-0000-4000-8000-000000000005'
    or c.edition_key is distinct from 'money2020:asia:2027'
    or c.is_demo is distinct from false
    or c.name is distinct from 'Money20/20 Asia 2027'
    or c.start_date is distinct from '2027-04-27'
    or c.end_date is distinct from '2027-04-29'
    or c.city is distinct from 'Bangkok'
    or c.country is distinct from 'Thailand'
    or c.region is distinct from NULL
    or c.vertical is distinct from 'fintech'
    or c.estimated_audience_size is distinct from NULL
    or c.lifecycle_status is distinct from 'scheduled'
    or c.needs_review is distinct from false
    or c.review_reason is distinct from NULL
    or c.source_url is distinct from 'https://asia.money2020.com/attend'
    or c.source_name is distinct from 'Money20/20'
    or not (c.accepted_evidence @> '{"name":{"sourceUrl":"https://asia.money2020.com/attend","sourceName":"Money20/20","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Money20/20 Asia 2027 is an advertised upcoming edition."},"startDate":{"sourceUrl":"https://asia.money2020.com/attend","sourceName":"Money20/20","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Upcoming edition starts 2027-04-27."},"endDate":{"sourceUrl":"https://asia.money2020.com/attend","sourceName":"Money20/20","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Upcoming edition ends 2027-04-29."},"city":{"sourceUrl":"https://asia.money2020.com/attend","sourceName":"Money20/20","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Bangkok is the announced host city."},"country":{"sourceUrl":"https://asia.money2020.com/attend/plan-your-trip","sourceName":"Money20/20","checkedAt":"2026-10-01T18:53:01Z","excerpt":"The official 2027 trip page specifies Bangkok, Thailand."},"vertical":{"sourceUrl":"https://asia.money2020.com/attend","sourceName":"Money20/20","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Editorial mapping to the existing fintech vertical, supported by: The event targets the fintech ecosystem, including payments firms and banks; cross-border payment partnerships are described."},"lifecycleStatus":{"sourceUrl":"https://asia.money2020.com/attend","sourceName":"Money20/20","checkedAt":"2026-10-01T18:53:01Z","excerpt":"Organizer advertises this future edition; no cancellation notice was found in the checked edition information."},"targetAudience":{"sourceUrl":"https://asia.money2020.com/attend","sourceName":"Money20/20","checkedAt":"2026-10-01T18:53:01Z","excerpt":"The event targets the fintech ecosystem, including payments firms and banks; cross-border payment partnerships are described."}}'::jsonb)
  then raise exception 'Conference facts/evidence changed; review before applying'; end if;
  if exists (select 1 from jsonb_each('{"audienceLeadership2027":{"sourceUrl":"https://asia.money2020.com/attend","sourceName":"Money20/20 Asia","checkedAt":"2026-10-01T20:18:14Z","excerpt":"The official upcoming-2027 attendance section identifies one in three attendees as C-suite; the same page describes senior decision-makers across the fintech and payments ecosystem. The 5,000+ claim remains a lower bound, not an exact attendance forecast."}}'::jsonb) e
    where c.accepted_evidence ? e.key and c.accepted_evidence->e.key is distinct from e.value)
  then raise exception 'New evidence key conflicts; review before applying'; end if;
  if c.target_audience_fit is not distinct from 100
    and c.target_audience_assessment is not distinct from '{"input":{"rubricVersion":"grain-target-audience-v1","reviewState":"reviewed","reviewedAt":"2026-10-01T20:18:14Z","reviewedBy":"Developer-approved official-source assessment review","factors":{"audience":{"tags":[{"tag":"payment_companies","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"banks","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"fintech_businesses","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"relevance":{"tags":[{"tag":"cross_border_payments","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"payments","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"leadership":{"tags":[{"tag":"c_suite","evidenceRefs":["audienceLeadership2027"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null}}},"result":{"rubricVersion":"grain-target-audience-v1","supportedScoreFloor":100,"complete":true,"acceptedScore":100,"unresolvedFactors":[],"pendingReview":false,"components":[{"factor":"audience","maximum":60,"points":60,"resolved":true,"awardedTags":[{"tag":"payment_companies","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"relevance","maximum":25,"points":25,"resolved":true,"awardedTags":[{"tag":"cross_border_payments","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"leadership","maximum":15,"points":15,"resolved":true,"awardedTags":[{"tag":"c_suite","evidenceRefs":["audienceLeadership2027"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null}]}}'::jsonb
    and c.accepted_evidence @> '{"audienceLeadership2027":{"sourceUrl":"https://asia.money2020.com/attend","sourceName":"Money20/20 Asia","checkedAt":"2026-10-01T20:18:14Z","excerpt":"The official upcoming-2027 attendance section identifies one in three attendees as C-suite; the same page describes senior decision-makers across the fintech and payments ecosystem. The 5,000+ claim remains a lower bound, not an exact attendance forecast."}}'::jsonb then
    null; -- Identical reviewed state: retry does not increment revision.
  elsif c.target_audience_fit is not distinct from NULL
    and c.target_audience_assessment is not distinct from '{"input":{"rubricVersion":"grain-target-audience-v1","reviewState":"reviewed","reviewedAt":"2026-10-01T19:07:08Z","reviewedBy":"Lead integration review of collected evidence","factors":{"audience":{"tags":[{"tag":"payment_companies","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"banks","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"fintech_businesses","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"relevance":{"tags":[{"tag":"cross_border_payments","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"payments","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"leadership":{"tags":[],"resolved":false,"resolutionEvidenceRefs":[],"unresolvedReason":"Relevant leadership seniority is not verified in the collected audience evidence."}}},"result":{"rubricVersion":"grain-target-audience-v1","supportedScoreFloor":85,"complete":false,"acceptedScore":null,"unresolvedFactors":[{"factor":"leadership","reason":"Relevant leadership seniority is not verified in the collected audience evidence."}],"pendingReview":false,"components":[{"factor":"audience","maximum":60,"points":60,"resolved":true,"awardedTags":[{"tag":"payment_companies","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"relevance","maximum":25,"points":25,"resolved":true,"awardedTags":[{"tag":"cross_border_payments","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"leadership","maximum":15,"points":null,"resolved":false,"awardedTags":[],"resolutionEvidenceRefs":[],"unresolvedReason":"Relevant leadership seniority is not verified in the collected audience evidence."}]}}'::jsonb then
    update public.conferences
    set target_audience_fit = 100,
        target_audience_assessment = '{"input":{"rubricVersion":"grain-target-audience-v1","reviewState":"reviewed","reviewedAt":"2026-10-01T20:18:14Z","reviewedBy":"Developer-approved official-source assessment review","factors":{"audience":{"tags":[{"tag":"payment_companies","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"banks","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"fintech_businesses","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"relevance":{"tags":[{"tag":"cross_border_payments","evidenceRefs":["targetAudience"],"reviewed":true},{"tag":"payments","evidenceRefs":["targetAudience"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null},"leadership":{"tags":[{"tag":"c_suite","evidenceRefs":["audienceLeadership2027"],"reviewed":true}],"resolved":true,"resolutionEvidenceRefs":[],"unresolvedReason":null}}},"result":{"rubricVersion":"grain-target-audience-v1","supportedScoreFloor":100,"complete":true,"acceptedScore":100,"unresolvedFactors":[],"pendingReview":false,"components":[{"factor":"audience","maximum":60,"points":60,"resolved":true,"awardedTags":[{"tag":"payment_companies","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"relevance","maximum":25,"points":25,"resolved":true,"awardedTags":[{"tag":"cross_border_payments","evidenceRefs":["targetAudience"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null},{"factor":"leadership","maximum":15,"points":15,"resolved":true,"awardedTags":[{"tag":"c_suite","evidenceRefs":["audienceLeadership2027"]}],"resolutionEvidenceRefs":[],"unresolvedReason":null}]}}'::jsonb,
        accepted_evidence = accepted_evidence || '{"audienceLeadership2027":{"sourceUrl":"https://asia.money2020.com/attend","sourceName":"Money20/20 Asia","checkedAt":"2026-10-01T20:18:14Z","excerpt":"The official upcoming-2027 attendance section identifies one in three attendees as C-suite; the same page describes senior decision-makers across the fintech and payments ecosystem. The 5,000+ claim remains a lower bound, not an exact attendance forecast."}}'::jsonb,
        updated_at = now(), revision = revision + 1
    where id = '20000001-0000-4000-8000-000000000005';
  else raise exception 'Audience assessment changed; review before applying'; end if;
  insert into public.conference_observations (id, conference_id, edition_key, source_url, source_name, checked_at, verified_at, fetch_status, content_hash, evidence, extracted_facts, proposed_changes, issues, review_state, reviewed_at)
  values ('30000002-0000-4000-8000-000000000005', '20000001-0000-4000-8000-000000000005', 'money2020:asia:2027', 'https://asia.money2020.com/attend', 'Money20/20 Asia', '2026-10-01T20:18:14Z', '2026-10-01T20:18:14Z', 'success', NULL, '[{"sourceUrl":"https://asia.money2020.com/attend","sourceName":"Money20/20 Asia","checkedAt":"2026-10-01T20:18:14Z","excerpt":"The official upcoming-2027 attendance section identifies one in three attendees as C-suite; the same page describes senior decision-makers across the fintech and payments ecosystem. The 5,000+ claim remains a lower bound, not an exact attendance forecast."}]', '{"targetAudienceFit":100}', '{}', '["Overall ICP remains incomplete: estimatedAudienceSize, region. Attendance and geography were not changed."]', 'accepted', '2026-10-01T20:18:14Z') on conflict (id) do nothing;
  if exists (select 1 from public.conference_observations o where o.id = '30000002-0000-4000-8000-000000000005' and (
      o.id is distinct from '30000002-0000-4000-8000-000000000005'
      or o.conference_id is distinct from '20000001-0000-4000-8000-000000000005'
      or o.edition_key is distinct from 'money2020:asia:2027'
      or o.source_url is distinct from 'https://asia.money2020.com/attend'
      or o.source_name is distinct from 'Money20/20 Asia'
      or o.checked_at is distinct from '2026-10-01T20:18:14Z'
      or o.verified_at is distinct from '2026-10-01T20:18:14Z'
      or o.fetch_status is distinct from 'success'
      or o.content_hash is distinct from NULL
      or o.evidence is distinct from '[{"sourceUrl":"https://asia.money2020.com/attend","sourceName":"Money20/20 Asia","checkedAt":"2026-10-01T20:18:14Z","excerpt":"The official upcoming-2027 attendance section identifies one in three attendees as C-suite; the same page describes senior decision-makers across the fintech and payments ecosystem. The 5,000+ claim remains a lower bound, not an exact attendance forecast."}]'::jsonb
      or o.extracted_facts is distinct from '{"targetAudienceFit":100}'::jsonb
      or o.proposed_changes is distinct from '{}'::jsonb
      or o.issues is distinct from '["Overall ICP remains incomplete: estimatedAudienceSize, region. Attendance and geography were not changed."]'::jsonb
      or o.review_state is distinct from 'accepted'
      or o.reviewed_at is distinct from '2026-10-01T20:18:14Z'))
  then raise exception 'Review observation ID conflicts; transaction aborted'; end if;
end $review$;
commit;
