"use client";
import Link from "next/link";
import { useState } from "react";
import { geographicRegions } from "@/lib/geography";
import { scoringFactors, type ExplainedConferenceScore } from "@/lib/conference-scoring";
import type { Conference } from "@/types";
import { TierBadge } from "@/components/ui";
const verticalLabels = { fintech: "Fintech", ecommerce: "Ecommerce", travel: "Travel", saas: "SaaS" };
const fieldStyle = "mt-2 block min-h-12 w-full rounded-lg border border-slate-300 bg-white px-3 py-2";
export function ConferenceDiscovery({ conferences }: { conferences: { conference: Conference; scoring: ExplainedConferenceScore }[] }) {
 const [search,setSearch] = useState(""); const [vertical,setVertical] = useState(""); const [region,setRegion] = useState(""); const [tier,setTier] = useState("");
 const resetFilters = () => { setSearch(""); setVertical(""); setRegion(""); setTier(""); };
 const query = search.trim().toLowerCase();
 const visible = conferences.filter(({conference:c,scoring}) => (!vertical || c.vertical === vertical) && (!region || c.region === region) && (!tier || scoring.tier === tier) && `${c.name} ${c.city} ${c.country} ${verticalLabels[c.vertical]} ${geographicRegions[c.region].label}`.toLowerCase().includes(query)).sort((a,b) => b.scoring.score-a.scoring.score || a.conference.startDate.localeCompare(b.conference.startDate) || a.conference.id.localeCompare(b.conference.id));
 return <div className="space-y-6"><div><p className="text-xs font-semibold uppercase tracking-widest text-slate-500">Discover & prioritize</p><h1 className="mt-2 text-3xl font-semibold md:text-4xl">Conferences</h1><p className="mt-3 text-sm text-slate-600">Find the events closest to your ideal customer profile. Compare fit, then open the score breakdown to see what drives each result.</p><p className="mt-3 text-xs text-slate-500">Synthetic demo events · All fixture dates included · Ranked by ICP score</p></div>
 <details className="rounded-xl border border-slate-200 bg-[#eef3e7] p-4 text-sm"><summary className="cursor-pointer font-semibold">How ICP scoring works</summary><div className="mt-3 space-y-2 leading-6"><p>Each component is scored from 0–100. Total = vertical × 40% + target audience × 30% + audience size × 15% + geography × 15%, rounded once to the nearest whole number.</p><p>Tier A: 80–100 · Tier B: 60–79 · Tier C: below 60.</p><p>Demo assumptions: fintech 100, ecommerce 85, travel 70, SaaS 40. Audience fit comes directly from each fixture.</p><p>Audience size: 1,000+ attendees = 100; 500–999 = 80; 250–499 = 60; 1–249 = 40; zero = 0.</p><p>Geography: Southeast England 100, Benelux 85, Central Israel 80, US Northeast 75, San Francisco Bay Area 60. These are assumed market priorities, not distance calculations.</p></div></details>
 <section aria-label="Conference filters" className="grid gap-4 rounded-xl border border-slate-200 bg-white p-5 sm:grid-cols-2 xl:grid-cols-4"><label className="text-xs font-semibold">Search conferences or locations<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, city, country…" className={fieldStyle}/></label><label className="text-xs font-semibold">Vertical<select className={fieldStyle} value={vertical} onChange={e=>setVertical(e.target.value)}><option value="">All verticals</option>{Object.entries(verticalLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="text-xs font-semibold">Geography<select className={fieldStyle} value={region} onChange={e=>setRegion(e.target.value)}><option value="">All regions</option>{Object.entries(geographicRegions).map(([v,{label}])=><option key={v} value={v}>{label}</option>)}</select></label><label className="text-xs font-semibold">ICP tier<select className={fieldStyle} value={tier} onChange={e=>setTier(e.target.value)}><option value="">All tiers</option><option value="A">A · 80–100</option><option value="B">B · 60–79</option><option value="C">C · Below 60</option></select></label></section>
 <div className="flex justify-between text-sm"><p role="status">{visible.length} of {conferences.length} conferences</p>{(search||vertical||region||tier)&&<button onClick={resetFilters} className="underline">Clear filters</button>}</div>
 {!visible.length ? <div className="rounded-xl border border-dashed p-10 text-center"><h2>No conferences match these filters</h2><p>Try a broader search or clear your filters to see all demo events.</p><button onClick={resetFilters} className="mt-5 underline">Clear filters</button></div> : <div className="grid items-start gap-4 md:grid-cols-2">{visible.map(({conference:c,scoring})=><article key={c.id} className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="p-5"><div className="flex justify-between"><span className="text-xs uppercase">{verticalLabels[c.vertical]}</span><TierBadge tier={scoring.tier}/></div><h2 className="mt-4 text-lg font-semibold">{c.name}</h2><Link href={`/leads?conferenceId=${c.id}`} className="mt-3 inline-block rounded-lg border border-[#294b25] px-3 py-2 text-sm font-semibold text-[#294b25]">Quick Capture →</Link><p className="mt-2 text-sm text-slate-600"><time dateTime={c.startDate}>{c.startDate}</time>{c.endDate !== c.startDate && ` – ${c.endDate}`}</p><p className="mt-1 text-sm text-slate-600">{c.city}, {c.country} · {geographicRegions[c.region].label}</p><div className="mt-5 flex justify-between border-t pt-4"><div><p className="text-xs">Estimated audience</p><p>{c.estimatedAudienceSize.toLocaleString("en-US")} attendees</p></div><div><p className="text-xs">ICP score</p><p className="text-2xl font-semibold">{scoring.score}<span className="text-sm font-normal"> / 100</span></p></div></div></div><details className="border-t bg-[#fafbf8] p-5"><summary className="cursor-pointer text-sm font-semibold text-[#294b25]">Why this score? <span className="sr-only">{c.name}</span></summary><ul className="mt-4 space-y-4">{scoring.breakdown.map(item=><li key={item.factor}><div className="flex flex-wrap justify-between gap-2 text-sm"><span className="font-semibold">{scoringFactors[item.factor].label} · {item.weight*100}%</span><span>{item.rawScore}/100 → <strong>{item.weightedContribution.toFixed(2)} points</strong></span></div><div aria-hidden="true" className="mt-2 h-1.5 rounded-full bg-slate-200"><div className="h-full rounded-full bg-[#76a34c]" style={{width:`${item.rawScore}%`}}/></div><p className="mt-2 text-xs leading-5 text-slate-600">{item.reason}</p></li>)}</ul><p className="mt-4 border-t pt-3 text-xs">Weighted sum {scoring.breakdown.reduce((sum,item)=>sum+item.weightedContribution,0).toFixed(2)} → rounded total {scoring.score}/100 → Tier {scoring.tier}. A ≥ 80; B ≥ 60; C &lt; 60.</p></details></article>)}</div>}</div>;
}
